docs: FF-59 Added OOP library usage example
ioet/ioet-feature-flag pull request #36
Opened 2023-09-23 01:10 UTC by Mikkel-14

#### 🤔 Why?

- Since it's needed to add another example of the same email body but using OOP and dependency injection for best practices

#### 🛠 What I changed:

- Extracted the previous example to its own file
- Created a new file with the OOP example
- Linked both markdown files to the README

#### 🗃️ Jira Issues:

- [FF-59](https://ioetec.atlassian.net/browse/FF-59)

#### 🚦 Functional Testing Results:

N/A

2023-09-25 02:06 UTC, FranLMSP approved these changes
🦀

2023-09-25 18:02 UTC, Ghigog commented on usage_examples/object_oriented_usage.md
> +> **Note:** Even though sending a toggle context is optinal, the parameter declaration on the decision function is *required* and needs to be defaulted to `None`.
I think you mean "optional"

2023-09-25 18:02 UTC, Ghigog commented on usage_examples/object_oriented_usage.md
> +    Your order number 3456 has bee approved.
"been" approved

2023-09-25 18:03 UTC, Ghigog commented on usage_examples/object_oriented_usage.md
> +    Your order number 3456 has bee approved.
aqui tambien "been" approved

2023-09-25 18:03 UTC, Ghigog commented on usage_examples/functional_usage.md
> +    Your order number {sales_order_number} has bee approved.
"been" approved

2023-09-25 18:04 UTC, Ghigog commented on usage_examples/object_oriented_usage.md
> +            Your order number {sales_order_number} has bee approved.
"been" approved

2023-09-25 18:04 UTC, Ghigog commented on usage_examples/object_oriented_usage.md
> +            Your order number {sales_order_number} has bee approved.
"been" approved

2023-09-25 18:04 UTC, Ghigog requested changes
Just a couple things to change, search and replace "bee" with "been"

2023-09-27 17:59 UTC, Ghigog approved these changes
LGTM 👍

2023-09-27 18:00 UTC, merged